# Generated by Django 4.0.6 on 2022-12-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, verbose_name='status')),
                ('full_name', models.CharField(max_length=200, verbose_name='full_name')),
                ('tel', models.CharField(max_length=200, verbose_name='tel')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
                ('login', models.CharField(max_length=200, verbose_name='login')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
            ],
        ),
    ]
