# Generated by Django 4.0.6 on 2022-12-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourphoto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='photo_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='full_name')),
                ('photo', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('login', models.CharField(max_length=200, verbose_name='login')),
            ],
        ),
    ]
