# Generated by Django 4.0.6 on 2022-12-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourphoto', '0002_photo_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200, verbose_name='login')),
                ('city', models.CharField(max_length=200, verbose_name='city')),
            ],
        ),
    ]
