# Generated by Django 4.1.3 on 2022-12-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourphoto', '0003_city_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='city',
            field=models.CharField(default='', max_length=200, verbose_name='city'),
        ),
    ]
