# Generated by Django 4.1.3 on 2022-12-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourphoto', '0004_users_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
