# Generated by Django 4.0.6 on 2022-12-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourphoto', '0005_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_list',
            name='photo',
            field=models.CharField(max_length=200, verbose_name='image'),
        ),
    ]
