# Generated by Django 4.0.6 on 2022-12-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourphoto', '0006_alter_photo_list_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_profile', models.CharField(max_length=400, verbose_name='photo_profile')),
                ('login', models.CharField(max_length=200, verbose_name='login')),
            ],
        ),
    ]
